"""empty message

Revision ID: 1cdba94c56fd
Revises: 2735bccc1838
Create Date: 2015-05-31 23:13:01.650260

"""

# revision identifiers, used by Alembic.
revision = '1cdba94c56fd'
down_revision = '2735bccc1838'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
