"""empty message

Revision ID: 2735bccc1838
Revises: 3004709d13fc
Create Date: 2015-05-31 23:08:06.866096

"""

# revision identifiers, used by Alembic.
revision = '2735bccc1838'
down_revision = '3004709d13fc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallets', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'wallets', 'users', ['user_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wallets', type_='foreignkey')
    op.drop_column('wallets', 'user_id')
    ### end Alembic commands ###
