"""empty message

Revision ID: 37ecf17aa04d
Revises: 1cdba94c56fd
Create Date: 2015-05-31 23:53:49.184487

"""

# revision identifiers, used by Alembic.
revision = '37ecf17aa04d'
down_revision = '1cdba94c56fd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
