"""empty message

Revision ID: 37ffdf7056bd
Revises: 37ecf17aa04d
Create Date: 2015-06-01 20:22:49.659814

"""

# revision identifiers, used by Alembic.
revision = '37ffdf7056bd'
down_revision = '37ecf17aa04d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
