"""empty message

Revision ID: 3f77e540b018
Revises: 4e4d002575a9
Create Date: 2015-06-01 20:27:59.016676

"""

# revision identifiers, used by Alembic.
revision = '3f77e540b018'
down_revision = '4e4d002575a9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
