"""empty message

Revision ID: 4e4d002575a9
Revises: 37ffdf7056bd
Create Date: 2015-06-01 20:24:46.460404

"""

# revision identifiers, used by Alembic.
revision = '4e4d002575a9'
down_revision = '37ffdf7056bd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
